packages:
  # all packages in direct subdirs of packages/
  - 'server'
  # all packages in subdirs of components/
  - 'react'
  - 'vue3'
  # exclude packages that are inside test directories
  # - '!**/test/**'